### ISSUE TITLE
Math equations are not correctly displayed

### ISSUE THREAD

**Issue by rinconraul** [DesignSafe-CI/DS-User-Guide#44]
# Overview

Math equations in the use cases (and any other page) will not be correctly rendered.

![image](https://github.com/DesignSafe-CI/DS-User-Guide/assets/61350784/13d5bc05-6b1c-4134-9346-bf62e4a5eac4)

# MathJax - Possible solution (test 1)

Adding to `mkdocs.yml`:
```
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
```

It works, but at the same time, it also renders HTML-style code:

![image](https://github.com/DesignSafe-CI/DS-User-Guide/assets/61350784/55224c9b-f50d-4798-a505-e0dbb0fcc470)

# KaTeX - It seems this is not a solution (test 2)

Adding to `mkdocs.yml`:
```
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
```

It does not render the equations, it displays HTML code, and it seems it brings back to the previous theme.

![image](https://github.com/DesignSafe-CI/DS-User-Guide/assets/61350784/7439c8a7-a7b0-4cd2-be02-6202205462cf)

**Comment by wesleyboar** [comment]
**Yes, the `mkdocs.yml` must be updated to support this.**

I used MathJax successfully (no `{ ... }`  rendering errors), but (since #46 a.k.a. redesign) one must be careful not to lose TACC's `extra_css` and `extra_javascript`.

<details><summary>changes to configuration</summary>

The `- ...` represents all entries from the URL in the comment after it.

```yml
extra_javascript:
  # TACC/TACC-Docs:/mkdocs.base.yml
  - ... # https://github.com/TACC/TACC-Docs/blob/main/mkdocs.base.yml#L38-L40
  # DesignSafe/DS-User-Guide
  # https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#loading-mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
```

```yml
markdown_extensions:
  # TACC/TACC-Docs:/mkdocs.base.yml
  - ... # https://github.com/TACC/TACC-Docs/blob/main/mkdocs.base.yml#L45-L65
  # DesignSafe/DS-User-Guide
  # https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#loading-mathjax
  - pymdownx.arithmatex:
      generic: true
```

You may see and test [the complete changeset](https://github.com/DesignSafe-CI/DS-User-Guide/compare/feat/gh-44-support-math-poc-do-not-merge). This is a proof-of-concept. Do not create a PR with this change.

</details>

**To make this less of a mess to configure, I will make changes upstream ([TACC/TACC-Docs](https://github.com/TACC/TACC-Docs)).**
